/** Localized copy for finance research reports. */

import type { ReportLanguage } from './report-language.ts'
import type { MethodologyCategory } from './methodology.ts'

/** Section titles owned by the report writer. */
export type ReportSectionKey =
  | 'summary' | 'researchQuestion' | 'marketSnapshot' | 'priceAction' | 'technicalIndicators' | 'synthesis'
  | 'predictionMarket' | 'methodologyCoverage' | 'investorLenses' | 'valuationFramework' | 'financialQuality'
  | 'investmentView' | 'projectAndCommunity'
  | 'earningsReview' | 'eventContext' | 'industryLandscape' | 'competitivePosition' | 'macroDrivers'
  | 'ratesCredit' | 'commodityBalance' | 'fxDrivers' | 'fundFlows' | 'onchainTokenomics' | 'allocation'
  | 'scenarioAnalysis' | 'catalysts' | 'monitoringPlan' | 'dataRequirements' | 'strategyGaps' | 'riskAndLimitations'

/** Line labels owned by the report writer. */
export type ReportLabelKey =
  | 'asOf' | 'price' | 'change' | 'bars' | 'source' | 'syntheticSuffix' | 'horizon' | 'compositeScore'
  | 'confidence' | 'noConflicts' | 'conflicts' | 'impliedProbability' | 'bidAsk' | 'spread' | 'volume'
  | 'openInterest' | 'resolution' | 'rules' | 'atrPercent' | 'fixtureLimitation' | 'snapshotLimitation'
  | 'notAdvice' | 'defaultQuestion' | 'defaultHorizon' | 'returnWindow' | 'rangePosition' | 'drawdown'
  | 'volumeTrend' | 'scenarioBull' | 'scenarioBase' | 'scenarioBear' | 'riskBudget' | 'atrStop'
  | 'positionSize' | 'monitoringCadence' | 'requiresInputs' | 'focus' | 'blockMissing'
  | 'stanceAccumulate' | 'stanceWatch' | 'stanceReduce' | 'viewStance' | 'viewConfidence'
  | 'viewReasons' | 'viewInvalidation' | 'viewGaps' | 'maStack' | 'rsiOverbought' | 'rsiOversold'
  | 'rsiNeutral' | 'macdBullish' | 'macdBearish'
  | 'riskBars' | 'gapCount' | 'obvAverage'

/** Interpolated line templates owned by the report writer. */
export type ReportTemplateKey =
  | 'summary' | 'signal' | 'reading' | 'investor' | 'investorRisk' | 'gap' | 'reportTitle'
  | 'htmlMeta' | 'htmlPill' | 'htmlRange' | 'htmlTooltip'
  | 'invalidation' | 'invalidationInverse' | 'viewBreadth' | 'viewStrongest' | 'viewRisk'

/** Chrome labels of the interactive HTML report. */
export type ReportHtmlKey =
  | 'eyebrow' | 'cardPrice' | 'cardChange' | 'cardComposite' | 'cardAtr' | 'chartTitle' | 'chartAria'
  | 'rangeAll' | 'navAria' | 'footer'

/** Category copy rendered in report headers, focus lines, and catalysts. */
export interface ReportCategoryCopy {
  readonly name: string
  /** Research questions this category centers on. */
  readonly focus: readonly string[]
  /** Inputs the category needs beyond a price history. */
  readonly requirements: readonly string[]
  /** Expected catalyst families for the category. */
  readonly catalysts: readonly string[]
}

/** One input-demanding section block: what it needs and what it would check. */
export interface ReportBlockCopy {
  readonly requires: readonly string[]
  readonly checks: readonly string[]
}

/** Per-lens copy rendered in the investor lens section. */
export interface LensCopy {
  readonly school: string
  readonly questions: readonly string[]
  readonly risk: string
}

/** Localized copy consumed by the report writer. */
export interface ReportCopy {
  readonly htmlLang: string
  readonly titleSuffix: string
  readonly sections: Readonly<Record<ReportSectionKey, string>>
  readonly labels: Readonly<Record<ReportLabelKey, string>>
  readonly templates: Readonly<Record<ReportTemplateKey, string>>
  readonly html: Readonly<Record<ReportHtmlKey, string>>
  /** Reading and strategy-gap notes keyed by methodology id; `{placeholders}` are interpolated. */
  readonly notes: Readonly<Record<string, string>>
  /** Investor lens copy keyed by lens id. */
  readonly lenses: Readonly<Record<string, LensCopy>>
  /** Localized direction words; absent entries keep the canonical token. */
  readonly directions: Readonly<Record<string, string>>
  /** Localized weighted-signal names; absent entries keep the canonical token. */
  readonly signals: Readonly<Record<string, string>>
  /** Localized execution statuses; absent entries keep the canonical token. */
  readonly statuses: Readonly<Record<string, string>>
  /** Localized methodology categories; absent entries keep the canonical token. */
  readonly categories: Partial<Record<MethodologyCategory, string>>
  /** Localized catalog entry names keyed by entry id; absent entries keep the canonical name. */
  readonly catalogNames: Readonly<Record<string, string>>
  /** Localized data requirements keyed by the canonical requirement; absent entries keep the canonical text. */
  readonly requirements: Readonly<Record<string, string>>
  /** Locale labels for the instrument metrics a report quotes. */
  readonly metrics: Readonly<Record<string, string>>
  /** Report category copy keyed by category id. */
  readonly reportCategories: Readonly<Record<string, ReportCategoryCopy>>
  /** Report form display names keyed by form id. */
  readonly reportForms: Readonly<Record<string, string>>
  /** Input-demanding section blocks keyed by section id. */
  readonly blocks: Readonly<Record<string, ReportBlockCopy>>
}

const EN: ReportCopy = {
  htmlLang: 'en',
  titleSuffix: 'research report',
  sections: {
    investmentView: 'Investment View',
    summary: 'Summary',
    researchQuestion: 'Research Question',
    marketSnapshot: 'Market Snapshot',
    priceAction: 'Price Action',
    technicalIndicators: 'Technical Indicators',
    synthesis: 'Multi-Indicator Synthesis',
    predictionMarket: 'Prediction Market',
    methodologyCoverage: 'Methodology Coverage',
    investorLenses: 'Investor Lenses',
    valuationFramework: 'Valuation Framework',
    financialQuality: 'Financial Quality',
    earningsReview: 'Earnings Review',
    eventContext: 'Event Context',
    industryLandscape: 'Industry Landscape',
    competitivePosition: 'Competitive Position',
    macroDrivers: 'Macro Drivers',
    ratesCredit: 'Rates And Credit',
    commodityBalance: 'Supply And Demand Balance',
    fxDrivers: 'FX Drivers',
    fundFlows: 'Fund Flows And Positioning',
    onchainTokenomics: 'On-chain And Tokenomics',
    projectAndCommunity: 'Project And Community',
    allocation: 'Allocation And Risk Budget',
    scenarioAnalysis: 'Scenario Analysis',
    catalysts: 'Catalysts',
    monitoringPlan: 'Monitoring Plan',
    dataRequirements: 'Data Requirements',
    strategyGaps: 'Strategy Gaps',
    riskAndLimitations: 'Risk And Limitations',
  },
  labels: {
    stanceAccumulate: 'Accumulate — the structure supports adding',
    stanceWatch: 'Watch — wait for a cleaner signal',
    stanceReduce: 'Reduce — the evidence has turned against the position',
    viewStance: 'Stance: ',
    viewConfidence: 'Conviction: ',
    viewReasons: 'What supports this view',
    viewInvalidation: 'What would change this view',
    viewGaps: 'What this report still cannot see',
    maStack: 'Moving-average stack: {direction}',
    rsiOverbought: 'overbought, so late entries carry more risk',
    rsiOversold: 'oversold, so reversal and breakdown risk both apply',
    rsiNeutral: 'mid-range',
    macdBullish: 'MACD above its signal line',
    macdBearish: 'MACD below its signal line',
    riskBars: 'size the position from the ATR stop below',
    gapCount: 'Missing inputs: ',
    obvAverage: '20-bar average ',
    asOf: 'As-of: ',
    price: 'Price: ',
    change: 'Change: ',
    bars: 'Bars: ',
    source: 'Source: ',
    syntheticSuffix: ' (synthetic fixture)',
    horizon: 'Horizon: ',
    compositeScore: 'Composite score: ',
    confidence: 'Confidence: ',
    noConflicts: 'No directional conflicts across the weighted signals.',
    conflicts: 'Conflicting signals: ',
    impliedProbability: 'Implied probability: ',
    bidAsk: 'Bid/ask: ',
    spread: 'spread ',
    volume: 'Volume: ',
    openInterest: 'Open interest: ',
    resolution: 'Resolution: ',
    rules: 'Rules: ',
    atrPercent: 'ATR as percent of price: ',
    fixtureLimitation: 'The initial provider is deterministic fixture data and is not live market data.',
    snapshotLimitation: 'Snapshot source: {provider}; upstream availability, latency, and data quality remain external.',
    notAdvice: 'The report is research automation output, not investment advice.',
    defaultQuestion: 'Assess the current research setup.',
    defaultHorizon: 'swing',
    returnWindow: 'Window return: ',
    rangePosition: 'Range position: ',
    drawdown: 'Drawdown from window high: ',
    volumeTrend: 'Volume vs 20-bar mean: ',
    scenarioBull: 'Bull case (+2 ATR): ',
    scenarioBase: 'Base case (spot): ',
    scenarioBear: 'Bear case (-2 ATR): ',
    riskBudget: 'Risk budget example (1% of equity): ',
    atrStop: 'ATR stop distance: ',
    positionSize: 'Indicative position size: ',
    monitoringCadence: 'Cadence: ',
    requiresInputs: 'Required inputs: ',
    focus: 'Research focus: ',
    blockMissing: 'This snapshot cannot supply this section yet.',
  },
  templates: {
    summary: '{direction} bias for {label}. {direction} composite with {aligned} aligned signals.',
    signal: '- {name}: {direction} (weight {weight}, value {value})',
    reading: '- {name}: {direction}, {confidence}% confidence, status {status}. {note}',
    investor: '- {name} ({school}): {stance}.',
    investorRisk: '  - Risk: {risk}',
    gap: '- {name} ({category}): {status}; requires {requirements}',
    reportTitle: '{label} · {category} {form}',
    htmlMeta: '{symbol} · {currency} · As of {asOf} · Source {provider}',
    htmlPill: '{direction} · {confidence}% confidence',
    htmlRange: '{count} bars',
    htmlTooltip: '<strong>{time}</strong><br>Close {close}<br>Volume {volume}',
    invalidation: 'A close above {level} (SMA 20) would invalidate the bearish read.',
    invalidationInverse: 'A close below {level} (SMA 20) would invalidate the bullish read.',
    viewBreadth: '{aligned}/{total} weighted signals point {direction}',
    viewStrongest: '{name}: {direction}, weight {weight}',
    viewRisk: 'Risk budget: ATR is {atr} of price; {risk}',
  },
  html: {
    eyebrow: 'DeepSeek Harness · Finance Research',
    cardPrice: 'Price',
    cardChange: 'Change',
    cardComposite: 'Composite',
    cardAtr: 'ATR',
    chartTitle: 'Interactive price chart',
    chartAria: 'Interactive price chart',
    rangeAll: 'All',
    navAria: 'Report sections',
    footer: 'Generated by DeepSeek Harness finance research. This is research automation output, not investment advice.',
  },
  notes: {
    'ma-trend': 'EMA12 {ema12} vs EMA26 {ema26}',
    donchian: '{window}-day range {low}–{high}',
    adx: 'ADX {adx}',
    supertrend: 'ATR-band trend direction',
    roc: '20-bar rate of change',
    macd: 'MACD histogram direction',
    rsi: 'RSI14 {rsi}',
    'rsi-reversion': 'RSI extreme state',
    bollinger: 'Bollinger z-score',
    kdj: 'K/D cross and level',
    'volume-price': 'Volume {volume} vs 20-period mean {mean}',
    obv: 'OBV vs 20-bar average',
    vwap: 'Rolling 20-bar VWAP proxy',
    'volume-profile': 'OHLCV bucket profile, not intraday footprint',
    chan: 'Simplified structure proxy; full Chan segmentation requires dedicated analysis',
    dow: 'Confirmed swing structure',
    'price-action': 'SMA/price structure proxy',
    'volatility-breakout': 'Latest range versus ATR',
    cycle: 'Autocorrelation cycle proxy',
    elliott: 'Wave counts require validated labeling; no automatic count is claimed',
    wyckoff: 'Accumulation/distribution requires footprint and event context',
    gap: 'Requires: {requirements}',
  },
  lenses: {
    buffett: { school: 'Value and quality', questions: ['Does the business have a durable moat?', 'Is free cash flow durable?', 'Is the price sensible versus intrinsic value?'], risk: 'Quality and valuation inputs are absent from the current snapshot.' },
    graham: { school: 'Deep value', questions: ['Is there a margin of safety?', 'Are earnings and assets stable?'], risk: 'Fundamental and balance-sheet inputs are absent.' },
    munger: { school: 'Quality compounding', questions: ['Can the business compound for a decade?', 'What can permanently impair it?'], risk: 'Business quality is not represented by price and volume alone.' },
    lynch: { school: 'Growth at a reasonable price', questions: ['Is growth visible and understandable?', 'Is the valuation reasonable?'], risk: 'Growth and earnings estimates are absent.' },
    soros: { school: 'Reflexivity and macro', questions: ['What belief is changing?', 'Where is the trend self-reinforcing?'], risk: 'Macro positioning and reflexivity inputs are absent.' },
    dalio: { school: 'Macro and risk balance', questions: ['What regime are we in?', 'Is risk balanced across drivers?'], risk: 'Macro regime and portfolio data are absent.' },
    simons: { school: 'Quantitative signals', questions: ['Is the signal statistically robust?', 'What is the turnover and cost?'], risk: 'No backtest, cost model, or out-of-sample validation is present.' },
    livermore: { school: 'Trend following', questions: ['Is the trend confirmed?', 'Where is the stop?'], risk: 'Position sizing and execution assumptions are absent.' },
    marks: { school: 'Cycle and risk', questions: ['Where are we in the cycle?', 'What is priced in?'], risk: 'Cycle position cannot be established from one asset alone.' },
    taleb: { school: 'Tail risk and convexity', questions: ['What is the worst plausible path?', 'Is the payoff convex?'], risk: 'Tail distribution and option data are absent.' },
  },
  directions: {},
  signals: {},
  statuses: {},
  categories: {},
  catalogNames: {},
  metrics: {
    eps: 'Diluted EPS',
    bookValuePerShare: 'Book value per share',
    roe: 'Return on equity',
    netMargin: 'Net margin',
    operatingMargin: 'Operating margin',
    revenueGrowth: 'Revenue growth (YoY)',
    profitGrowth: 'Net profit growth (YoY)',
    debtRatio: 'Debt-to-asset ratio',
    currentRatio: 'Current ratio',
    cashConversion: 'Operating cash flow / net profit',
    rank: 'Market rank',
    marketCap: 'Market cap',
    peTtm: 'P/E (TTM)',
    peStatic: 'P/E (last full year)',
    peRatio: 'P/E',
    pegRatio: 'PEG',
    pbRatio: 'P/B',
    psRatio: 'P/S',
    evToEbitda: 'EV/EBITDA',
    dividendYield: 'Dividend yield',
    analystTargetPrice: 'Analyst target price',
    epsTtm: 'EPS (TTM)',
    peers: 'Peers',
    epsGrowth: 'EPS growth (TTM YoY)',
    roa: 'Return on assets',
    revenueGrowthQoq: 'Revenue growth (QoQ)',
    earningsGrowthQoq: 'Earnings growth (QoQ)',
    beta: 'Beta',
    sector: 'Sector',
    industry: 'Industry',
    pb: 'P/B',
    peVsIndustry: 'Static P/E vs industry weighted average',
    industryName: 'Industry',
    industryPe: 'Industry P/E (weighted average)',
    industryPeMedian: 'Industry P/E (median)',
    industryPeArithmetic: 'Industry P/E (arithmetic mean)',
    industryPeCompanies: 'Companies behind the industry average',
    peVsIndustryMedian: 'Static P/E vs industry median',
    fullyDilutedMarketCap: 'Fully diluted market cap',
    marketCapDominance: 'Market cap dominance',
    volume24h: '24h volume',
    volumeChange24h: '24h volume change',
    change24h: '24h change',
    change7d: '7d change',
    change30d: '30d change',
    change90d: '90d change',
    circulatingSupply: 'Circulating supply',
    totalSupply: 'Total supply',
    maxSupply: 'Max supply',
    twitterFollowers: 'Twitter followers',
    redditSubscribers: 'Reddit subscribers',
    telegramUsers: 'Telegram users',
    sentimentUp: 'Community sentiment (up)',
    sentimentDown: 'Community sentiment (down)',
    watchlistUsers: 'CoinGecko watchlist users',
    githubWatchers: 'GitHub watchers',
    githubOpenIssues: 'GitHub open issues',
    githubStars: 'GitHub stars',
    githubForks: 'GitHub forks',
    githubCommits4w: 'GitHub commits (4 weeks)',
    githubSubscribers: 'GitHub watchers (legacy)',
    githubClosedIssues: 'GitHub closed issues',
  },
  requirements: {},
  reportCategories: {
    macro: { name: 'Macro', focus: ['growth, inflation, and policy direction', 'rates, liquidity, and transmission', 'cross-asset implications'], requirements: ['national accounts', 'inflation series', 'policy rates and balance sheets'], catalysts: ['policy meetings and rate decisions', 'inflation and labour prints', 'fiscal and geopolitical events'] },
    industry: { name: 'Industry', focus: ['market size and demand drivers', 'value chain and supply-demand balance', 'competition, policy, and substitution'], requirements: ['industry size and growth series', 'value-chain participants', 'policy and capacity data'], catalysts: ['demand data and channel checks', 'capacity and pricing announcements', 'policy and subsidy changes'] },
    equity: { name: 'Equity', focus: ['earnings power and quality', 'valuation versus intrinsic value', 'catalysts, ownership, and risk'], requirements: ['financial statements', 'earnings estimates and guidance', 'peer and valuation multiples'], catalysts: ['earnings and guidance', 'capital actions and ownership', 'product, pricing, and regulatory events'] },
    fund: { name: 'Fund and ETF', focus: ['strategy, exposure, and holdings', 'tracking, liquidity, and cost', 'flows and performance attribution'], requirements: ['holdings and weights', 'flows and premium-discount', 'benchmark and fee schedule'], catalysts: ['rebalance and index events', 'flow and premium shifts', 'fee and mandate changes'] },
    'fixed-income': { name: 'Rates and Credit', focus: ['duration, curve, and rate path', 'credit spread and default risk', 'carry, roll, and liquidity'], requirements: ['yield curves', 'issuer financials and covenants', 'credit spreads and ratings'], catalysts: ['central-bank decisions', 'supply and auction calendars', 'rating actions and defaults'] },
    'commodity-fx': { name: 'Commodity and FX', focus: ['supply-demand balance and inventories', 'cost curve and marginal producer', 'rates, terms of trade, and currency drivers'], requirements: ['inventories and supply-demand balances', 'cost curves and futures term structure', 'rate differentials and balance of payments'], catalysts: ['inventory and production reports', 'OPEC and policy decisions', 'rate decisions and intervention'] },
    crypto: { name: 'Crypto', focus: ['network, tokenomics, and adoption', 'liquidity, flows, and market structure', 'regulation, security, and regime shifts'], requirements: ['on-chain metrics', 'token unlock and supply schedule', 'exchange and ETF flows'], catalysts: ['protocol upgrades and unlocks', 'ETF and exchange flows', 'regulation and enforcement'] },
    strategy: { name: 'Strategy', focus: ['asset allocation and risk budget', 'style, sector, and factor rotation', 'positioning, valuation, and catalysts'], requirements: ['index valuation and earnings', 'fund flows and positioning', 'macro regime series'], catalysts: ['policy and macro regime shifts', 'positioning and flow extremes', 'seasonality and index events'] },
  },
  reportForms: {
    flash: 'Flash note',
    daily: 'Daily',
    weekly: 'Weekly',
    monthly: 'Monthly',
    'deep-dive': 'Deep dive',
    thematic: 'Thematic',
    event: 'Event review',
    earnings: 'Earnings review',
    allocation: 'Allocation',
    data: 'Data report',
  },
  blocks: {
    'valuation-framework': { requires: ['financial statements', 'earnings estimates', 'peer multiples', 'discount rate'], checks: ['Which multiple is defensible for this business model?', 'What growth and margin assumptions does the price imply?', 'Where does it trade versus its own history and peers?'] },
    'financial-quality': { requires: ['income statement', 'balance sheet', 'cash-flow statement'], checks: ['Are margins and returns on capital durable?', 'Is cash conversion consistent with reported earnings?', 'How much leverage funds the returns?'] },
    'earnings-review': { requires: ['reported actuals', 'consensus estimates', 'segment breakdown', 'guidance'], checks: ['Which line items beat or missed?', 'Is the beat driven by volume, price, mix, or one-offs?', 'What changed in guidance and backlog?'] },
    'event-context': { requires: ['event timeline', 'announcement text', 'pre-event expectation'], checks: ['What changed versus the prior state?', 'How did price and volume react on the event bar?', 'Which assets transmit the impact?'] },
    'industry-landscape': { requires: ['industry size and growth', 'capacity and utilization', 'policy and regulation'], checks: ['What drives demand over the next 12 months?', 'Where is capacity tight or oversupplied?', 'Which policy or technology shift changes the structure?'] },
    'competitive-position': { requires: ['peer set', 'market share and unit economics', 'cost position'], checks: ['Who holds pricing power and why?', 'What is the cost or switching-cost moat?', 'Which competitor can compress returns?'] },
    'macro-drivers': { requires: ['GDP and activity series', 'inflation series', 'policy rate path'], checks: ['Which driver dominates the current regime?', 'What is priced into rates and the curve?', 'Which sectors carry the transmission risk?'] },
    'rates-credit': { requires: ['yield curve', 'credit spreads', 'issuer financials'], checks: ['Where is duration risk concentrated?', 'How much compensation does the spread offer?', 'Which refinancing wall matters?'] },
    'commodity-balance': { requires: ['inventories', 'supply-demand balance', 'cost curve'], checks: ['Is the market in surplus or deficit?', 'What is the marginal cost of supply?', 'How does the curve price storage and scarcity?'] },
    'fx-drivers': { requires: ['rate differentials', 'balance of payments', 'positioning'], checks: ['Which leg drives the pair?', 'Is the move carry, terms of trade, or risk sentiment?', 'What policy shift would break the trend?'] },
    'fund-flows': { requires: ['fund holdings', 'flows and premium-discount', 'benchmark and fees'], checks: ['What exposure does the fund actually carry?', 'How do flows interact with the price trend?', 'What tracking or liquidity cost applies?'] },
    'onchain-tokenomics': { requires: ['on-chain activity metrics', 'token unlock schedule', 'exchange and ETF flows'], checks: ['Is network usage growing with price?', 'What supply pressure comes from unlocks?', 'Which venue or issuer concentrates flow?'] },
    'project-and-community': { requires: ['developer activity', 'community size', 'sentiment'], checks: ['Is development still active?', 'Is the community growing or fading?', 'Does sentiment diverge from price?'] },
  },
}

const ZH: ReportCopy = {
  htmlLang: 'zh',
  titleSuffix: '研究报告',
  sections: {
    investmentView: '投资结论',
    summary: '摘要',
    researchQuestion: '研究问题',
    marketSnapshot: '行情快照',
    priceAction: '价格行为',
    technicalIndicators: '技术指标',
    synthesis: '多指标综合',
    predictionMarket: '预测市场',
    methodologyCoverage: '方法论覆盖',
    investorLenses: '投资大师视角',
    valuationFramework: '估值框架',
    financialQuality: '财务质量',
    earningsReview: '业绩点评',
    eventContext: '事件背景',
    industryLandscape: '行业格局',
    competitivePosition: '竞争格局',
    macroDrivers: '宏观驱动',
    ratesCredit: '利率与信用',
    commodityBalance: '供需平衡',
    fxDrivers: '汇率驱动',
    fundFlows: '资金与持仓',
    onchainTokenomics: '链上与代币经济',
    projectAndCommunity: '项目进展与社区',
    allocation: '配置与风险预算',
    scenarioAnalysis: '情景分析',
    catalysts: '催化剂',
    monitoringPlan: '跟踪计划',
    dataRequirements: '数据需求',
    strategyGaps: '策略缺口',
    riskAndLimitations: '风险与限制',
  },
  labels: {
    stanceAccumulate: '可增持 — 结构支持继续加仓',
    stanceWatch: '观望 — 等待更清晰的信号',
    stanceReduce: '减仓 — 证据已转向不利',
    viewStance: '立场：',
    viewConfidence: '置信度：',
    viewReasons: '支撑该结论的证据',
    viewInvalidation: '结论推翻条件',
    viewGaps: '本报告暂时看不到的维度',
    maStack: '均线排列：{direction}',
    rsiOverbought: '偏超买，此处追高的风险收益变差',
    rsiOversold: '偏超卖，反弹与破位风险并存',
    rsiNeutral: '中性区间',
    macdBullish: 'MACD 在信号线上方',
    macdBearish: 'MACD 在信号线下方',
    riskBars: '仓位应按下方 ATR 止损设定',
    gapCount: '缺少输入：',
    obvAverage: '20 根均值 ',
    asOf: '截至：',
    price: '价格：',
    change: '涨跌幅：',
    bars: 'K 线数：',
    source: '数据来源：',
    syntheticSuffix: '（合成 fixture 数据）',
    horizon: '周期：',
    compositeScore: '综合评分：',
    confidence: '置信度：',
    noConflicts: '加权信号之间没有方向冲突。',
    conflicts: '冲突信号：',
    impliedProbability: '隐含概率：',
    bidAsk: '买/卖价：',
    spread: '价差 ',
    volume: '成交量：',
    openInterest: '未平仓量：',
    resolution: '结算规则：',
    rules: '规则：',
    atrPercent: 'ATR 占价格比例：',
    fixtureLimitation: '初始 Provider 为确定性 fixture 数据，不是实时行情。',
    snapshotLimitation: '快照来源：{provider}；上游可用性、延迟与数据质量仍属外部因素。',
    notAdvice: '本报告是研究自动化输出，不构成投资建议。',
    defaultQuestion: '评估当前研究环境。',
    defaultHorizon: '波段',
    returnWindow: '区间收益：',
    rangePosition: '区间位置：',
    drawdown: '距区间高点回撤：',
    volumeTrend: '成交量对 20 根均值：',
    scenarioBull: '乐观情景（+2 ATR）：',
    scenarioBase: '基准情景（现价）：',
    scenarioBear: '悲观情景（-2 ATR）：',
    riskBudget: '风险预算示例（权益 1%）：',
    atrStop: 'ATR 止损距离：',
    positionSize: '参考仓位：',
    monitoringCadence: '跟踪频率：',
    requiresInputs: '所需输入：',
    focus: '研究重点：',
    blockMissing: '当前快照尚无法提供本节内容。',
  },
  templates: {
    summary: '{label} 呈{direction}。{aligned} 个信号与综合方向一致。',
    invalidation: '收盘站上 {level}（20 日均线）将推翻看跌结论。',
    invalidationInverse: '收盘跌破 {level}（20 日均线）将推翻看涨结论。',
    viewBreadth: '{aligned}/{total} 个加权信号指向{direction}',
    viewStrongest: '最强信号 {name}：{direction}，权重 {weight}',
    viewRisk: '风险预算：ATR 占价格 {atr}；{risk}',
    signal: '- {name}：{direction}（权重 {weight}，数值 {value}）',
    reading: '- {name}：{direction}，置信度 {confidence}%，状态 {status}。{note}',
    investor: '- {name}（{school}）：{stance}。',
    investorRisk: '  - 风险：{risk}',
    gap: '- {name}（{category}）：{status}；需要 {requirements}',
    reportTitle: '{label} · {category}{form}',
    htmlMeta: '{symbol} · {currency} · 截至 {asOf} · 来源 {provider}',
    htmlPill: '{direction} · 置信度 {confidence}%',
    htmlRange: '{count} 根',
    htmlTooltip: '<strong>{time}</strong><br>收盘 {close}<br>成交量 {volume}',
  },
  html: {
    eyebrow: 'DeepSeek Harness · Finance Research',
    cardPrice: '最新价',
    cardChange: '涨跌幅',
    cardComposite: '综合评分',
    cardAtr: 'ATR',
    chartTitle: '交互式价格图',
    chartAria: '交互式价格图',
    rangeAll: '全部',
    navAria: '报告章节',
    footer: '由 DeepSeek Harness 金融研究生成。本报告是研究自动化输出，不构成投资建议。',
  },
  notes: {
    'ma-trend': 'EMA12 {ema12} 对比 EMA26 {ema26}',
    donchian: '{window} 日区间 {low}–{high}',
    adx: 'ADX {adx}',
    supertrend: 'ATR 通道趋势方向',
    roc: '20 根 K 线变化率',
    macd: 'MACD 柱状图方向',
    rsi: 'RSI14 {rsi}',
    'rsi-reversion': 'RSI 极值状态',
    bollinger: '布林带 z-score',
    kdj: 'K/D 交叉与位置',
    'volume-price': '成交量 {volume} 对比 20 期均值 {mean}',
    obv: 'OBV 对比 20 根均值',
    vwap: '20 根滚动 VWAP 代理',
    'volume-profile': 'OHLCV 分桶筹码分布，不是日内足迹',
    chan: '简化结构代理；完整缠论分段需要专门分析',
    dow: '已确认的摆动结构',
    'price-action': 'SMA/价格结构代理',
    'volatility-breakout': '最新振幅对比 ATR',
    cycle: '自相关周期代理',
    elliott: '波浪计数需要经验证的标注，本报告不声称自动计数',
    wyckoff: '吸筹/派发判断需要足迹与事件背景',
    gap: '需要：{requirements}',
  },
  lenses: {
    buffett: { school: '价值与质量', questions: ['这家企业是否有持久的护城河？', '自由现金流是否可持续？', '价格相对内在价值是否合理？'], risk: '当前快照缺少质量与估值输入。' },
    graham: { school: '深度价值', questions: ['是否存在安全边际？', '盈利与资产是否稳定？'], risk: '缺少基本面与资产负债表输入。' },
    munger: { school: '优质复利', questions: ['这家企业能否复利十年？', '什么会永久损害它？'], risk: '仅凭价格与成交量无法代表企业质量。' },
    lynch: { school: '合理价格的成长', questions: ['成长是否可见且可理解？', '估值是否合理？'], risk: '缺少成长与盈利预测。' },
    soros: { school: '反身性与宏观', questions: ['正在变化的是什么信念？', '趋势在哪里自我强化？'], risk: '缺少宏观仓位与反身性输入。' },
    dalio: { school: '宏观与风险平衡', questions: ['我们处在什么状态？', '风险是否在各驱动因素间平衡？'], risk: '缺少宏观状态与组合数据。' },
    simons: { school: '量化信号', questions: ['信号是否统计稳健？', '换手与成本是多少？'], risk: '缺少回测、成本模型与样本外验证。' },
    livermore: { school: '趋势跟随', questions: ['趋势是否得到确认？', '止损位在哪里？'], risk: '缺少仓位管理与执行假设。' },
    marks: { school: '周期与风险', questions: ['我们处在周期的什么位置？', '价格已经反映了什么？'], risk: '仅凭单一资产无法判断周期位置。' },
    taleb: { school: '尾部风险与凸性', questions: ['最坏的可信路径是什么？', '收益结构是否凸性？'], risk: '缺少尾部分布与期权数据。' },
  },
  signals: {
    trend: '趋势',
    momentum: '动量',
    macd: 'MACD',
    'mean-reversion': '均值回归',
    participation: '参与度',
  },
  directions: {
    bullish: '看涨',
    bearish: '看跌',
    neutral: '中性',
    'insufficient-data': '数据不足',
    constructive: '偏积极',
    cautious: '偏谨慎',
  },
  statuses: {
    available: '可计算',
    partial: '部分可计算',
    'requires-input': '需要额外输入',
    'not-data-backed': '无数据支撑',
  },
  categories: {
    breakout: '突破',
    trend: '趋势',
    momentum: '动量',
    'mean-reversion': '均值回归',
    'statistical-arbitrage': '统计套利',
    'price-volume': '价量',
    'market-structure': '市场结构',
    'wave-cycle': '波浪与周期',
    factor: '因子',
    fundamental: '基本面',
    'event-driven': '事件驱动',
    'machine-learning': '机器学习',
    microstructure: '微观结构',
  },
  catalogNames: {
    turtle: '海龟交易法',
    'ma-trend': '均线趋势',
    donchian: '唐奇安通道',
    adx: 'ADX 趋势',
    supertrend: 'SuperTrend',
    momentum: '动量',
    roc: 'ROC',
    macd: 'MACD',
    rsi: 'RSI',
    'relative-strength': '相对强弱',
    'rsi-reversion': 'RSI 均值回归',
    bollinger: '布林带均值回归',
    kdj: 'KDJ',
    grid: '网格',
    pairs: '配对交易',
    'volume-price': '量价关系',
    obv: 'OBV',
    vwap: 'VWAP',
    'volume-profile': '筹码分布',
    chan: '缠论',
    dow: '道氏理论',
    'price-action': '价格行为',
    wyckoff: '威科夫',
    elliott: '艾略特波浪',
    cycle: '周期分析',
    'opening-range': '开盘区间突破',
    'volatility-breakout': '波动率突破',
    'market-neutral': '市场中性',
    'pca-arb': 'PCA 套利',
    value: '价值因子',
    'factor-momentum': '动量因子',
    quality: '质量因子',
    'low-vol': '低波因子',
    size: '小市值因子',
    'multi-factor': '多因子',
    dcf: 'DCF 估值',
    'financial-quality': '财务质量',
    'industry-rotation': '行业轮动',
    earnings: '财报策略',
    'dividend-buyback': '分红与回购',
    'merger-arb': '并购套利',
    'index-rebalance': '指数调仓',
    forest: '随机森林',
    'boosted-trees': 'XGBoost / LightGBM',
    'sequence-model': 'LSTM / Transformer',
    reinforcement: '强化学习',
    'market-making': '做市',
    'order-flow': '订单流',
    execution: 'VWAP / TWAP 执行',
    'order-book': '订单簿失衡',
  },
  reportCategories: {
    macro: { name: '宏观', focus: ['增长、通胀与政策方向', '利率、流动性与传导', '跨资产含义'], requirements: ['国民经济核算', '通胀序列', '政策利率与资产负债表'], catalysts: ['政策会议与利率决议', '通胀与就业数据', '财政与地缘事件'] },
    industry: { name: '行业', focus: ['市场规模与需求驱动', '产业链与供需平衡', '竞争、政策与替代'], requirements: ['行业规模与增速', '产业链参与者', '政策与产能数据'], catalysts: ['需求数据与渠道调研', '产能与定价公告', '政策与补贴变化'] },
    equity: { name: '股票', focus: ['盈利能力与质量', '估值与内在价值', '催化剂、股东结构与风险'], requirements: ['财务报表', '盈利预测与指引', '同业与估值倍数'], catalysts: ['业绩与指引', '资本运作与股东变化', '产品、定价与监管事件'] },
    fund: { name: '基金与 ETF', focus: ['策略、暴露与持仓', '跟踪、流动性与成本', '资金流与业绩归因'], requirements: ['持仓与权重', '资金流与折溢价', '基准与费率'], catalysts: ['调仓与指数事件', '资金流与折溢价变化', '费率与投资范围变更'] },
    'fixed-income': { name: '债券与信用', focus: ['久期、曲线与利率路径', '信用利差与违约风险', 'Carry、骑乘与流动性'], requirements: ['收益率曲线', '发行人财务与条款', '信用利差与评级'], catalysts: ['央行决议', '供给与招标日程', '评级行动与违约'] },
    'commodity-fx': { name: '商品与外汇', focus: ['供需平衡与库存', '成本曲线与边际产能', '利率、贸易条件与汇率驱动'], requirements: ['库存与供需平衡表', '成本曲线与期限结构', '利差与国际收支'], catalysts: ['库存与产量报告', 'OPEC 与政策决议', '利率决议与干预'] },
    crypto: { name: '加密资产', focus: ['网络、代币经济与采用', '流动性、资金流与市场结构', '监管、安全与范式变化'], requirements: ['链上指标', '解锁与供应计划', '交易所与 ETF 资金流'], catalysts: ['协议升级与解锁', 'ETF 与交易所资金流', '监管与执法'] },
    strategy: { name: '策略与专题', focus: ['资产配置与风险预算', '风格、行业与因子轮动', '仓位、估值与催化剂'], requirements: ['指数估值与盈利', '资金流与仓位', '宏观状态序列'], catalysts: ['政策与宏观状态切换', '仓位与资金流极值', '季节性与指数事件'] },
  },
  reportForms: {
    flash: '快评',
    daily: '日报',
    weekly: '周报',
    monthly: '月报',
    'deep-dive': '深度报告',
    thematic: '专题报告',
    event: '事件点评',
    earnings: '财报点评',
    allocation: '配置报告',
    data: '数据报告',
  },
  blocks: {
    'valuation-framework': { requires: ['财务报表', '盈利预测', '同业估值', '折现率'], checks: ['哪种估值倍数适合该商业模式？', '当前价格隐含了怎样的增长与利润率？', '相对自身历史与同业处于什么位置？'] },
    'financial-quality': { requires: ['利润表', '资产负债表', '现金流量表'], checks: ['利润率与资本回报是否可持续？', '现金转化是否与报表利润一致？', '回报由多高的杠杆支撑？'] },
    'earnings-review': { requires: ['实际业绩', '市场一致预期', '分部数据', '管理层指引'], checks: ['哪些科目超预期或低于预期？', '超预期来自销量、价格、结构还是一次性因素？', '指引与在手订单有何变化？'] },
    'event-context': { requires: ['事件时间线', '公告原文', '事件前预期'], checks: ['相对事件前状态发生了什么变化？', '事件当根 K 线的价格与成交量如何反应？', '影响通过哪些资产传导？'] },
    'industry-landscape': { requires: ['行业规模与增速', '产能与利用率', '政策与监管'], checks: ['未来 12 个月的需求驱动是什么？', '产能偏紧还是过剩？', '哪项政策或技术变化改变行业结构？'] },
    'competitive-position': { requires: ['可比公司', '市场份额与单位经济', '成本地位'], checks: ['谁掌握定价权，为什么？', '成本或转换成本护城河有多深？', '哪个竞争对手可能压缩回报？'] },
    'macro-drivers': { requires: ['GDP 与活动指标', '通胀序列', '政策利率路径'], checks: ['当前状态下哪个驱动占主导？', '利率与曲线已计入什么？', '哪些板块承担传导风险？'] },
    'rates-credit': { requires: ['收益率曲线', '信用利差', '发行人财务'], checks: ['久期风险集中在哪一段？', '利差提供的补偿是否充分？', '哪个再融资高峰更关键？'] },
    'commodity-balance': { requires: ['库存', '供需平衡表', '成本曲线'], checks: ['市场处于过剩还是缺口？', '边际供给成本在哪里？', '期限结构如何反映库存与稀缺？'] },
    'fx-drivers': { requires: ['利差', '国际收支', '仓位'], checks: ['哪一条腿主导该货币对？', '驱动来自 carry、贸易条件还是风险偏好？', '什么政策变化会打破趋势？'] },
    'fund-flows': { requires: ['基金持仓', '资金流与折溢价', '基准与费率'], checks: ['基金实际承担了什么暴露？', '资金流与价格趋势如何相互影响？', '跟踪误差或流动性成本是多少？'] },
    'onchain-tokenomics': { requires: ['链上活跃度指标', '代币解锁计划', '交易所与 ETF 资金流'], checks: ['网络使用量是否与价格同步增长？', '解锁带来多大的供应压力？', '资金流集中在哪些交易所或发行方？'] },
    'project-and-community': { requires: ['开发活跃度', '社区规模', '情绪'], checks: ['开发是否仍然活跃？', '社区在增长还是流失？', '情绪与价格是否背离？'] },
  },
  metrics: {
    eps: '摊薄每股收益',
    bookValuePerShare: '每股净资产',
    roe: '净资产收益率',
    netMargin: '销售净利率',
    operatingMargin: '营业利润率',
    revenueGrowth: '营业收入同比',
    profitGrowth: '净利润同比',
    debtRatio: '资产负债率',
    currentRatio: '流动比率',
    cashConversion: '经营现金流/净利润',
    rank: '市值排名',
    marketCap: '市值',
    peTtm: '市盈率(TTM)',
    peStatic: '市盈率(静态)',
    peRatio: '市盈率',
    pegRatio: 'PEG',
    pbRatio: '市净率',
    psRatio: '市销率',
    evToEbitda: 'EV/EBITDA',
    dividendYield: '股息率',
    analystTargetPrice: '分析师目标价',
    epsTtm: '每股收益(TTM)',
    peers: '同业可比公司',
    epsGrowth: '每股收益同比',
    roa: '总资产收益率',
    revenueGrowthQoq: '营收环比',
    earningsGrowthQoq: '盈利环比',
    beta: 'Beta',
    sector: '板块',
    industry: '所属行业',
    pb: '市净率',
    peVsIndustry: '静态市盈率相对行业加权平均',
    industryName: '所属行业',
    industryPe: '行业市盈率(加权平均)',
    industryPeMedian: '行业市盈率(中位数)',
    industryPeArithmetic: '行业市盈率(算术平均)',
    industryPeCompanies: '行业均值覆盖公司数',
    peVsIndustryMedian: '静态市盈率相对行业中位数',
    fullyDilutedMarketCap: '全稀释市值',
    marketCapDominance: '市值占比',
    volume24h: '24小时成交额',
    volumeChange24h: '24小时成交额变化',
    change24h: '24小时涨跌',
    change7d: '7日涨跌',
    change30d: '30日涨跌',
    change90d: '90日涨跌',
    circulatingSupply: '流通量',
    totalSupply: '总供应量',
    maxSupply: '最大供应量',
    twitterFollowers: 'Twitter 关注数',
    redditSubscribers: 'Reddit 订阅数',
    telegramUsers: 'Telegram 用户数',
    sentimentUp: '社区看多比例',
    sentimentDown: '社区看空比例',
    watchlistUsers: 'CoinGecko 关注人数',
    githubWatchers: 'GitHub 关注者',
    githubOpenIssues: 'GitHub 未关闭 issue',
    githubStars: 'GitHub Star',
    githubForks: 'GitHub Fork',
    githubCommits4w: 'GitHub 近 4 周提交',
    githubSubscribers: 'GitHub 关注者（兼容字段）',
    githubClosedIssues: 'GitHub 已关闭 issue',
  },
  requirements: {
    'daily OHLCV': '日线 OHLCV',
    'account risk budget': '账户风险预算',
    OHLC: 'OHLC',
    'price history': '价格历史',
    'benchmark series': '基准序列',
    'peer universe': '同业标的池',
    'range bounds': '区间边界',
    'grid step': '网格步长',
    'capital budget': '资金预算',
    'paired asset history': '配对资产历史',
    OHLCV: 'OHLCV',
    'intraday volume and price': '日内成交量与价格',
    'intraday distribution': '日内分布',
    'structural validation': '结构验证',
    'swing confirmation': '摆动确认',
    'discretionary confirmation': '主观确认',
    'volume footprint': '成交量足迹',
    'event context': '事件背景',
    'validated wave labeling': '经验证的波浪标注',
    'sufficient history': '足够的历史数据',
    'cycle validation': '周期验证',
    'intraday bars': '日内 K 线',
    'session definition': '交易时段定义',
    'multi-asset universe': '多资产标的池',
    'hedge ratio': '对冲比率',
    'cross-sectional panel': '横截面面板数据',
    'fundamental data': '基本面数据',
    'asset universe': '资产标的池',
    'financial statements': '财务报表',
    'cross-sectional history': '横截面历史',
    'market-cap universe': '市值标的池',
    'fundamental and price panel': '基本面与价格面板',
    'cash-flow forecasts': '现金流预测',
    'discount rate': '折现率',
    'macro and industry data': '宏观与行业数据',
    estimates: '盈利预测',
    events: '事件数据',
    'corporate actions': '公司行为',
    'deal terms': '交易条款',
    probability: '概率估计',
    'index events': '指数事件',
    features: '特征',
    labels: '标签',
    validation: '验证集',
    'long sequence history': '长序列历史',
    simulator: '模拟器',
    'reward design': '奖励设计',
    'order book': '订单簿',
    'queue data': '排队数据',
    latency: '延迟数据',
    'tick and order-flow data': '逐笔与订单流数据',
    'order size': '订单规模',
    'market impact model': '市场冲击模型',
    'level-2 order book': 'Level-2 订单簿',
  },
}

/** Report copy for every shipped report language. */
export const REPORT_COPY: Record<ReportLanguage, ReportCopy> = { en: EN, zh: ZH }

/**
 * Interpolate one copy template.
 * @param template - Copy text carrying `{name}` placeholders.
 * @param params - Values keyed by placeholder name.
 * @returns The rendered copy.
 */
export function formatCopy(template: string, params: Readonly<Record<string, string | number>>): string {
  return template.replace(/\{([a-zA-Z0-9_-]+)\}/gu, (match, key: string) => {
    const value = params[key]
    return value === undefined ? match : String(value)
  })
}
